---
- name: OOM
  hosts: all
  sources:
    - ansible.eda.journald:
        match: ALL

  rules:
    - name: Match all on journald
      condition: event.journald.message is search("java.lang.OutOfMemoryError", ignorecase=false)
      action:
        run_playbook:
          name: playbooks/oom.yml
          extra_vars:
            log_entry: "{{ event.journald.message }}"
