---
- name: Check webserver
  hosts: all
  sources:
    - ansible.eda.journald:
        match: ALL

  rules:
    - name: Match all on journald
      condition: event.journald.message is search("EDA App is broken", ignorecase=false)
      action:
        run_playbook:
          name: playbooks/broken.yml
          extra_vars:
            log_entry: "{{ event.journald.message }}"
